steps:
  # Paso 1: Instalar las dependencias de Python
  - name: 'python'
    entrypoint: pip
    args: ["install", "-r", "utils/requirements.txt", "--user"]

  # Paso 2: Ejecutar el script que sube los DAGs y los Datos al bucket de Composer
  - name: 'python'
    entrypoint: python
    args:
      - "utils/add_dags_to_composer.py"
      - "--dags_directory=${_DAGS_DIRECTORY}"
      - "--dags_bucket=${_DAGS_BUCKET}"
      - "--data_directory=${_DATA_DIRECTORY}"

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _DAGS_DIRECTORY: "workflows/"
  _DAGS_BUCKET: "us-central1-demo-instance-a649b781-bucket" # Reemplaza con tu bucket de Composer
  _DATA_DIRECTORY: "data/"
